language: node_js

node_js:
  - "8"
  
test:
  adapter: mysql2
  database: test
  username: travis
  encoding: utf8

before_script:
- mysql -u root -e 'create database test character set utf8 collate utf8_general_ci;'
